export const mapVinylToSearch = (item) => ({
  id: item.id,
  slug: item.slug,
  title: item.title,
  subtitle: item.artist,
  category: "vinyl",
  image: item.image,
  description: item.description,
  price: item.price,
  rating: item.rating,
  variant: item.variant,
  salesCount: item.salesCount,
  dateAdded: item.dateAdded,
  releaseDate: item.releaseDate,
  tags: item.tags || [],
  genre: item.genre,
  route: `/vinyl/${item.slug}`,
});

export const mapMerchToSearch = (item) => ({
  id: item.id,
  slug: item.slug,
  title: item.name,
  subtitle: item.type,
  category: "merch",
  image: item.image,
  description: item.description,
  price: item.price,
  rating: item.rating,
  salesCount: item.salesCount,
  dateAdded: item.dateAdded,
  type: item.type,
  color: item.color,
  tags: item.tags || [],
  route: `/merch/${item.slug}`,
});

export const mapTechToSearch = (item) => ({
  id: item.id,
  slug: item.slug,
  title: item.name,
  subtitle: item.type,
  category: "tech",
  image: item.image,
  description: item.description,
  price: item.price,
  rating: item.rating,
  salesCount: item.salesCount,
  dateAdded: item.dateAdded,
  brand: item.brand,
  type: item.type,
  tags: item.tags || [],
  route: `/tech/${item.slug}`,
});
